camera0: 2
camera1: 0
frame_width: 640
frame_height: 360
read_from_previous_camera_intrinsics: 0
mono_calibration_frames: 10
stereo_calibration_frames: 15
view_resize: 1
checkerboard_box_size_scale : 3.35
checkerboard_rows: 4
checkerboard_columns: 7
cooldown: 100
checkerboard_box_size_scale_small : 3.35
checkerboard_box_size_scale_big : 4.2